const mongoose = require('mongoose');

const directSignalSchema = new mongoose.Schema({
    // A unique ID generated by MQL4 so you can update it later
    mqlSignalId: {
        type: String,
        required: true,
        unique: true,
        index: true,
    },
    indicatorName: {
        type: String,
        required: true,
    },
    pair: {
        type: String,
        required: true,
    },
    timeframe: {
        type: String,
        required: true,
    },
    direction: {
        type: String,
        enum: ['CALL', 'PUT'],
        required: true,
    },
    entryTime: {
        type: Date,
        required: true,
    },
    expirationTime: {
        type: Date,
        required: true,
    },
    status: {
        type: String,
        enum: ['PENDING', 'WIN', 'LOSS', 'DOJI'],
        default: 'PENDING',
    }
}, {
    timestamps: true // Adds createdAt and updatedAt automatically
});

const DirectSignal = mongoose.model('DirectSignal', directSignalSchema);

module.exports = DirectSignal;